a=float(input("Ingrese la nota del examen de Matematicas: "))
b=float(input("Ingrese la notas de las tres tareas de matematicas: "))
c=float(input(""))
d=float(input(""))
e=float(input("Ingrese la nota del examen de Fisica: "))
f=float(input("Ingrese la notas de las dos tareas de fisica: "))
g=float(input(""))
h=float(input("Ingrese la nota del examen de Quimica: "))
i=float(input("Ingrese la notas de las tres tareas de quimica: "))
j=float(input(""))
k=float(input(""))

aa=(a*0.90)
ab=(((b+c+d)/3)*0.10)
ac=(aa+ab)

ee=(e*0.80)
eb=(((f+g)/2)*0.20)
ec=(ee+eb)

hh=(h*0.85)
hb=(((i+j+k)/3)*0.15)
hc=(hh+hb)

tt=((ac+ec+hc)/3)
print(("La calificación de matematicas es: ")+str(ac))
print(("La calificación de fisica es: ")+str(ec))
print(("La calificación de quimica es: ")+str(hc))
print(("El promedio de las calificaciones es: ")+str(tt))